-- Tabelas para o Bio-Tracker

-- Tabela de Logs (Nova: para o chat)
CREATE TABLE IF NOT EXISTS public.chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    text TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, processing, completed, error
    response TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Dias
CREATE TABLE IF NOT EXISTS public.days (
    date DATE PRIMARY KEY,
    kcal_total INTEGER DEFAULT 0,
    ptn_total INTEGER DEFAULT 0,
    carb_total INTEGER DEFAULT 0,
    fat_total INTEGER DEFAULT 0,
    sleep_start TEXT,
    sleep_end TEXT,
    sleep_quality TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Refeições
CREATE TABLE IF NOT EXISTS public.meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE REFERENCES public.days(date) ON DELETE CASCADE,
    name TEXT NOT NULL,
    kcal INTEGER DEFAULT 0,
    ptn INTEGER DEFAULT 0,
    carb INTEGER DEFAULT 0,
    fat INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Itens de Refeição
CREATE TABLE IF NOT EXISTS public.meal_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id BIGINT REFERENCES public.meals(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    kcal INTEGER DEFAULT 0,
    ptn INTEGER DEFAULT 0,
    carb INTEGER DEFAULT 0,
    fat INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Habilitar RLS (Row Level Security) - Por enquanto permitindo acesso total com a key
ALTER TABLE public.days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_items ENABLE ROW LEVEL SECURITY;

-- Criar política de acesso público (temporária para setup)
CREATE POLICY "Permitir acesso total" ON public.days FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acesso total" ON public.meals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir acesso total" ON public.meal_items FOR ALL USING (true) WITH CHECK (true);
